apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-metrics-exporter.fullname" . }}
  labels:
    {{- include "azure-metrics-exporter.labels" . | nindent 4 }}
spec:
  # Tipo de servicio (ClusterIP = solo interno, NodePort = acceso externo)
  type: {{ .Values.service.type }}
  
  # Puertos que expone el servicio
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  
  # Selector: conecta con los pods del Deployment
  selector:
    {{- include "azure-metrics-exporter.selectorLabels" . | nindent 4 }}

